[INFO] внесены изменения, а именно: в файл urls.py добавлена конструкция if DEBUG: ...; в файле settings.py настройка DEBUG через int мне удобнее, так как 1 == True, 0 == False; в файл components/middleware.py добавить конструкцию if DEBUG: ...  не получилось, выдается: AttributeError: partially initialized module 'config.settings' has no attribute 'DEBUG' (most likely due to a circular import)